language: java
jdk:
  - oraclejdk8
script:
  mvn verify
after_failure:
  - cat codelab-config/target/surefire-reports/*.txt
  - cat codelab-registry/target/surefire-reports/*.txt
  - cat codelab-gateway/target/surefire-reports/*.txt
  - cat codelab-monitoring/target/surefire-reports/*.txt
