jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/codelab
  username: root
  password: root
  
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  connection:
    driver_class: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/codelab
    
on:
  port: 8888
  address: 0.0.0.0
 
admin:
  port: same
  address: 0.0.0.0
  
users:
  root:
    roles:
      - administrator
      - owner
    password: root